# Generated by Django 3.1.5 on 2021-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('DateTim', models.DateField()),
                ('Employees', models.IntegerField()),
                ('Assets', models.IntegerField()),
                ('Link', models.CharField(max_length=500)),
            ],
        ),
    ]
