# Generated by Django 3.1.5 on 2021-01-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dopodjanx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylist',
            old_name='DateTim',
            new_name='DateTime',
        ),
    ]
