# Generated by Django 3.1.5 on 2021-01-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dopodjanx', '0002_auto_20210117_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyList',
            new_name='CompanyInfo',
        ),
    ]
